image: maven:latest
pipelines:
  default:
    - step:
        script: 
          - openssl aes-256-cbc -pass pass:$GPG_PWD -in bitbucket-pipelines.gpg.enc -out bitbucket-pipelines.gpg -d
          - gpg --import bitbucket-pipelines.gpg
          - mvn -V -B -s bitbucket-pipelines.xml install