image: maven:latest
pipelines:
  branches:
    master:
        - step:
            script:
              - openssl aes-256-cbc -pass pass:$GPG_PWD -in bitbucket-pipelines.gpg.enc -out bitbucket-pipelines.gpg -d -md md5
              - gpg --import bitbucket-pipelines.gpg
              - mvn -V -B -s bitbucket-pipelines.xml deploy
    develop:
        - step:
            script:
              - openssl aes-256-cbc -pass pass:$GPG_PWD -in bitbucket-pipelines.gpg.enc -out bitbucket-pipelines.gpg -d -md md5
              - gpg --import bitbucket-pipelines.gpg
              - mvn -V -B -s bitbucket-pipelines.xml deploy
  default:
    - step:
        script:
          - mvn -V -B install -Dgpg.skip